//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onixa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesReplies
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int Message_Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Member_From_Id { get; set; }
        public Nullable<int> Member_To_Id { get; set; }
        public bool IsRead { get; set; }
        public string UserBy { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Members Members1 { get; set; }
        public virtual Messages_ Messages_ { get; set; }
    }
}
