//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onixa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        public int Id { get; set; }
        public string Platform { get; set; }
        public Nullable<int> Size { get; set; }
        public string Style { get; set; }
        public string Product_Tag { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int Product_Id { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
